### ISSUE TITLE
Stutter in playback in Flatpak version

### ISSUE THREAD

**Issue by machitgarha** [flathub/org.kde.elisa#144]
When using the Flatpak version, in some cases the music stutters (i.e. doesn't play for some milliseconds two or three times before playing). The packaged version doesn't have this problem (I'm on Fedora).

For instance, when you switch to the next/previous music, the first 4-5 seconds have noticeable glitches.

This issue is really annoying for me personally, because it keeps repeating in the beginning of every music I listen.

BTW, thanks for packaging it as Flatpak!

**Comment by travier** [comment]
This is likely https://bugs.kde.org/show_bug.cgi?id=443184

**Comment by machitgarha** [comment]
Yeah, I've tested it, and it seems to be the same issue. Thought when it happens only in the Flathub version, I should report it here. I'll continue the issue there. Thanks.
