### ISSUE TITLE
Elisa should suggest adding access to directories using Flatseal or KDE Flatpak permission page (was: Cannot load local files)

### ISSUE THREAD

**Issue by alex285** [flathub/org.kde.elisa#2]
*Output*
```
org.kde.kcoreaddons: Error loading plugin "kcm_elisa_local_file" "The shared library was not found." 
Plugin search paths are ("/app/lib64/plugins", "/usr/share/runtime/lib/plugins", "/usr/lib/plugins", "/app/bin") 
The environment variable QT_PLUGIN_PATH might be not correctly set
```
And also we cannot add folders, that i think it is a known issue with KDE Flatpak Portal?

ArchLinux
Flatpak: 0.11.4-1
xdg-desktop-portal: 0.11.1
xdg-desktop-portal-gtk: 0.11.1
xdg-desktop-portal-kde: 5.12.4

**Comment by mgallien** [comment]
@nedrichards thanks for having taken care of this.
@alex285 could you test if this fix your issue ?

**Comment by alex285** [comment]
@mgallien it works now thank you! 

But i noticed this. If we dont have Albums on $Music, but just some mp3, it cant load them. Is that expected behavior? Also I still cannot add any path outside $Music

**Comment by alex285** [comment]
Also I get
```
Qt: Session management error: Could not open network socket
```

**Comment by nedrichards** [comment]
@alex285 I have a bunch of random mp3s in that directory and they all seem to get detected. There may be some issues if the metadata is strange I suppose but @mgallien would be the expert there.

On the qt session management error can you run this from the command line:

> flatpak run --share=network org.kde.elisa

After I do that I get:

> Qt: Session management error: None of the authentication protocols specified are supported

Which would be expected since I'm not running a Qt focused distro so nothing's running there. It'd be annoying if we had to open an extra permission for all apps because of this though.

**Comment by mgallien** [comment]
We plan to add file system browsing in the next stable version. It is still not done.

With the current flatpak build, I had given the permission on your full file system. As far as I know, the portal API cannot be used to give access to a directory. I should go reach all flatpak people to discuss this and check if there is a solution.

I have always ignored the error about session mangement. I will check what it gives when ran in Plasma desktop.

**Comment by nedrichards** [comment]
Yeah - you can't get access to a directory with a portal.

**Comment by travier** [comment]
Should be fixed with https://github.com/flathub/org.kde.elisa/pull/127
