### ISSUE TITLE
Crash when scrolling through files in library

### ISSUE THREAD

**Issue by Erick555** [flathub/org.kde.elisa#29]
The app crashes about 50% of time when I scroll through files in my library:

`elisa[124893]: segfault at 58 ip 00006b0c4d8a5c70 sp 00007a70cdec4740 error 4 in libQt5Qml.so.5.15.2[6b0c4d6cc000+2d1000]
`
```
Thread 1 "elisa" received signal SIGSEGV, Segmentation fault.
QQmlIncubatorPrivate::incubate (this=0x100dd87a0, i=...) at qml/qqmlincubator.cpp:333
333                     if (!creator->requiredProperties().empty()) {
```
Attached full gdb output: [trace.log](https://github.com/flathub/org.kde.elisa/files/5647942/trace.log)

**Comment by tsdgeos** [comment]
Please report a bug in bugs.kde.org
