### ISSUE TITLE
Elisa does not open

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kde.elisa#4]
```
elisa: symbol lookup error: /lib/libKF5KCMUtils.so.5: undefined symbol: _ZN12KQuickAddons12ConfigModule10pagePushedEP10QQuickItem

```

**Comment by tsdgeos** [comment]
Hmmm, seems both the app and the runtime ship kdeclarative

./app/lib/libKF5Declarative.so.5.50.0
./usr/lib/libKF5Declarative.so.5.52.0

@mgallien I'd suggest the app stops doing it?

**Comment by mgallien** [comment]
> Hmmm, seems both the app and the runtime ship kdeclarative
> 
> ./app/lib/libKF5Declarative.so.5.50.0
> ./usr/lib/libKF5Declarative.so.5.52.0
> 
> @mgallien I'd suggest the app stops doing it?

@tsdgeos I am doing exactly that and also upgrading the framework version to match the runtime.

**Comment by mgallien** [comment]
Seems to work fine now.
LeandroStanger can you confirm and close this issue ?

**Comment by mgallien** [comment]
@tsdgeos thanks a lot for your help
