### ISSUE TITLE
Flatpak Elisa doesn't scan mp3 tags

### ISSUE THREAD

**Issue by JackH3103** [flathub/org.kde.elisa#51]
It seems as though Flatpak Elisa isn't scanning mp3 tags.

All my tracks from ~/Music are displayed in "Tracks" using the actual filename, but they do not appear in any of the other tabs (Albums, etc.).
Clicking the View Details button shows a duration of 00:00 and a rating of zero stars with no other information.
Attempting to change the stars gives the error "Data is not valid. Empty title."

Elisa from the openSUSE Tumbleweed repo has none of these issues.

**Comment by tsdgeos** [comment]
https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/66

**Comment by JackH3103** [comment]
Thanks, I can see the details in the View Details window now.
It seems like Elisa isn't actually using the tags though.
The tracks are still only showing in the Tracks view, Elisa is using the file name rather than the embedded track name, and there is no album art.

![tracks with file names](https://user-images.githubusercontent.com/23507259/147980195-5927a537-bab6-43b2-b0ed-159adc28bc0f.png)

**Comment by JackH3103** [comment]
Okay never mind; after refreshing the collection all the tracks are now properly organised. Thank you!

**Comment by JackH3103** [comment]
Reopening because it's happening again on version 21.12.1 updated today I think

**Comment by Justinzobel** [comment]
I can't reproduce this currently, if you are still seeing this issue please reopen this issue.
