### ISSUE TITLE
Flatpak Elisa uses wrong icons in dark mode

### ISSUE THREAD

**Issue by JackH3103** [flathub/org.kde.elisa#54]
![bad-icons](https://user-images.githubusercontent.com/23507259/148564138-b8785a46-bbfe-444b-b060-bb5b56f02788.png)

STEPS TO REPRODUCE:
1. Click Hamburger menu
2. Select colour scheme
3. Select Breeze Dark
4. Look at icons

EXPECTED RESULT:
Icons should be the dark theme icons

OBSERVED RESULT:
Icons are the light theme icons and blend in with the background

**Comment by aleixpol** [comment]
@Pointedstick I see you've done work on Elisa

@JackH3103 could you please report this to bugs.kde.org? This doesn't look like strictly a packaging issue.

**Comment by Pointedstick** [comment]
This should already be fixed upstream in https://invent.kde.org/multimedia/elisa/-/commit/595f5ca6dd11de165f93f71b84ecc1f5f204ad76. It should be in version 21.12.1.

**Comment by vulongm** [comment]
Could the issue be due to the "0001-force-Breeze-icon-theme.patch" patch?

**Comment by Pointedstick** [comment]
Seems like a patch that has outlived its usefulness. :)
