### ISSUE TITLE
Does not show in the system tray

### ISSUE THREAD

**Issue by cyclane** [flathub/org.kde.elisa#58]
By default Elisa (flatpak from flathub) does not show in the system tray with the "Keep running in system tray..." option enabled.

I found a workaround by setting `sockets=session-bus` (or enabling "D-Bus session bus" in Flatseal); however, I am unsure of the security implications of this and therefore cannot suggest it as a fix. 

Elisa version: 21.12.3
Flatpak version: 1.12.7
Desktop Environment: KDE Plasma 5.24.4 on Wayland

**Comment by Erick555** [comment]
sockets=session-bus is never good solition for such issues. You should run `--log-session-bus` to catch actual permission needed.
