### ISSUE TITLE
elisa with runtime 5.12 running on wayland doesn't have window decorations.

### ISSUE THREAD

**Issue by detrout** [flathub/org.kde.elisa#6]
When I upgraded to the 5.12 version commit 707a83bcff07a77e300621514b303a43d42e93c3a555979a9b80ecb4892a2e86 I lost the window decorations.

I suspect the problem is actually with org.kde.Platform. A simple qml file with a "text {}" box run with qmlscene  -platform wayland test.qml has no decorations in an elisa container launched like this.

```flatpak --devel run --command=bash org.kde.elisa```

But qmlscene -platform -wayland works fine outside the container and -platform xcb works both in the container and outside the container.

I'm not sure where to report bugs against the org.kde.Platform.

**Comment by mgallien** [comment]
Thanks for your report. I will try to reproduce it on my laptop.
The KDE runtime is maintained in the KDE Bugzilla. It is probably the best place to report such a bug.

**Comment by detrout** [comment]
Thank you

I forwarded the bug
https://bugs.kde.org/show_bug.cgi?id=406543

**Comment by travier** [comment]
This is very old and hopefully fixed by Should be fixed with https://github.com/flathub/org.kde.elisa/pull/127
