### ISSUE TITLE
Elisa uses gtk file picker when adding music collection.

### ISSUE THREAD

**Issue by raghu-kamath** [flathub/org.kde.elisa#77]
Elisa uses gtk file picker portal when I go to add music collection. This seems very out of place and behaves differently than the file picker I am used to. 

I am on fedora 36 kde spin and have xdg-desktop-portal-kde installed

**Comment by Erick555** [comment]
Do you have xdg-desktop-portal-gnome installed as well?

**Comment by raghu-kamath** [comment]
> Do you have xdg-desktop-portal-gnome installed as well?

Yes I do have three portals installed.

I asked around KDE matrix channels and Nicofee told me that it is because this bug -  https://bugs.kde.org/show_bug.cgi?id=458865

So I guess this can be closed here.

Thank you very much for your time.

**Comment by Erick555** [comment]
You shouldn't need xdg-desktop-portal-gnome when using KDE session. The xdg-desktop-portal-gtk is sufficient. Try removing xdg-desktop-portal-gnome and restart session.

**Comment by raghu-kamath** [comment]
I have not installed the gnome portal it was installed by default by my distro fedora. Alteast I do not remember installing it on purpose.

**Comment by raghu-kamath** [comment]
I have tried to remove gnome portal and also try with new test user. but the file picker then uses gtk portal instead of the kde one.

**Comment by raghu-kamath** [comment]
ONe thing to note is that this happens in xorg and not wayland

**Comment by Erick555** [comment]
Perhaps it's best to ask fedora to backport fix from kde/qt into their packages. This isn't flatpak elisa issue.
